### ISSUE TITLE
Crear un container únicamente con un nodo (sentry).

### ISSUE THREAD

**Issue by derfredy** [dragonstake/kira#3]
En tu portatil empezamos por un Dockerfile que haga lo siguiente:

1. Instala go y sus dependencias
2. Git clone del repo de sekai
3. Compila e instala el binario sekaid

Puedes empezar sin docker compilando en tu portatil directamente.

Cuando tengas el binario en tu ~/go/bin
puedes probar a ver la ayuda en línea que trae:

Por ejemplo:

sekaid init --help  Te dirá los flags de la inicialización de las carpetas y archivos de configuración. (Ojo el genesis que genera no sirve, es genérico y hay que cambiarlo por el de la propia red)
sekaid start --help   Te dirá los flags de arranque.

En la infraestructura de Kira lo lanzan así:
sekaid start --home=/root/.simapp

Los archivos de configuración y la bbdd quedan en esa ruta. Puedes entrar en tu instalación de kira y mirar el contenido.
Lo mínimo necesario para un nodo de este tipo es tener configurado el archivo config.toml y tener el genesis.json de la red que sea. Todos los nodos tienen el mismo genesis.json

El Dockerfile de kira
https://github.com/dragonstake/kira/blob/master/docker/kira/Dockerfile

**Comment by cano-devel** [comment]
He creado el contenedor con las siguientes características: 
* el dockerfile crea un contenedor para compilar y otro para ejecutar el binario sekaid
* la configuracion es tomada de un fichero llamado config.env
* he añadido algunos scripts para manipular el validador. En el script de "start_validator.sh" se tiene encuenta que no exista otra instancia.
